### ISSUE TITLE
Exemplar_Simulations.ipynb broke by ModuleNotFoundError: No module named 'mobilenetv2'

### ISSUE THREAD

**Issue by eMPee584** [coreylammie/MemTorch#104]
When running all cells on https://colab.research.google.com/github/coreylammie/MemTorch/blob/master/memtorch/examples/Exemplar_Simulations.ipynb an error is thrown:
![image](https://user-images.githubusercontent.com/1227833/136081063-0d3cd57c-e136-4982-a1a0-5ad263211168.png)

**Comment by coreylammie** [comment]
Hi @eMPee584,

Are you running the cell with hardware acceleration enabled? Training MobileNetV2 on the CIFAR-10 dataset using CPU (without hardware acceleration) will take a prohibitively long time, and will likely timeout on Google Colab. I believe default instances time out after ~12 hours of usage. 

Hardware acceleration can be enabled as follows on the free-tier of Google Colab using the following steps: `Go to Menu > Runtime > Change runtime.` `Change hardware acceleration to GPU.`. 

Please note that the first two cells do not directly use the `MemTorch` library, and instead rely on the `PyTorch` library. If you export all trained network parameters to a `.pt `representation, these can be used in conjunction with `memtorch` or `memtorch-cpu` in later cells. Please see the following tutorial for more information: [https://pytorch.org/tutorials/recipes/recipes/save_load_across_devices.html](https://pytorch.org/tutorials/recipes/recipes/save_load_across_devices.html).
