### ISSUE TITLE
[Bug] Changing Conductance states does not change test accuracy.

### ISSUE THREAD

**Issue by matifali** [coreylammie/MemTorch#140]
While running the [tutorial.ipynb](https://colab.research.google.com/github/coreylammie/MemTorch/blob/master/memtorch/examples/Tutorial.ipynb). Changing the number of finite conductance states does not have any effect on model test accuracy.

I tried finding the bug but could not.
Can anyone confirm? @coreylammie

**Comment by matifali** [comment]
just to keep it alive

**Comment by MAK13789** [comment]
I am having the same issue, don't know what's the reason for it though.

**Comment by P1terGuan** [comment]
Seems that the conductance matrix doesn't be quantized correctly, the crossbar still has many different conductance states even I set the parameter less than 10, is that caused by the way the network store weights or something else? (like using differential crossbar?)

**Comment by 24367452** [comment]
Hello, have you solved this problem? I am also troubled by this issue  @matifali @MAK13789 @P1terGuan
