### ISSUE TITLE
Fail to install memtorch using pip

### ISSUE THREAD

**Issue by patrick-chen-98** [coreylammie/MemTorch#146]
I tried to use different tools to install memtorch, they all give me error 
using pip install memtorch-cpu
![image](https://user-images.githubusercontent.com/79097916/200662504-8a45c44c-a628-45b7-8f8b-459ae6aeb99e.png)
using using pip install memtorch
![image](https://user-images.githubusercontent.com/79097916/200662846-b6cab58b-76c2-4483-aad5-ebae7ce7a696.png)

**Comment by spectacles9468** [comment]
Did you find any solution?
