### ISSUE TITLE
LINK : fatal error LNK1181: 

### ISSUE THREAD

**Issue by RookieoftheYear** [coreylammie/MemTorch#147]
hi, i try to run [python setup.py] install or [pip install memtorch] and got same error :
LINK : fatal error LNK1181: cannot open input file 'E:\pythonprojects\MemTorch\build\temp.win-amd64-3.6\Release\memtorch/cu\simulate_passive_kernel
s.obj'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181
did i miss something?

**Comment by matifali** [comment]
I would suggest you to choose another framework better. This is not being maintained anymore.

**Comment by RookieoftheYear** [comment]
@matifali thx bro，any recommendation? Plz

**Comment by RookieoftheYear** [comment]
fixed by reinstall vs c++ 2019 ,fuck it

**Comment by matifali** [comment]
You may try IBM aihwkit.
