### ISSUE TITLE
pip install memtorch error. Failed building wheel for memtorch

### ISSUE THREAD

**Issue by Xiaolili1028** [coreylammie/MemTorch#148]
![image](https://user-images.githubusercontent.com/92429590/209678146-2534e0f5-9934-4273-8820-e72625f1e0bf.png)
![image](https://user-images.githubusercontent.com/92429590/209679028-99d7e5d5-c1b9-4e56-bab5-50f0b338c6d7.png)
[log.txt](https://github.com/coreylammie/MemTorch/files/10308603/log.txt)

**Comment by patrick-chen-98** [comment]
use pip install memtorch==1.1.6

**Comment by spectacles9468** [comment]
> use pip install memtorch==1.1.6

But this doesn't work in colab. 
![image](https://github.com/coreylammie/MemTorch/assets/55502062/5fae2e13-c399-4847-a745-288b422bcc9d)
