### ISSUE TITLE
Check accuracy according to parameters

### ISSUE THREAD

**Issue by tnsrb02896** [coreylammie/MemTorch#155]
Hello, I am a university student living in Korea. I am studying deep learning through your memtorch code. Thanks to this memtorch code, it helped a lot, but I have a question, so I want to ask you a question. I would like to ask you a question about how VTEAM corrects the values of these parameters, such as r_on, r_off, etc., to reduce accuracy and increase accuracy. In conclusion, please tell me how to modify the values of the parameters.

**Comment by sheep1222** [comment]
> Hello, I am a university student living in Korea. I am studying deep learning through your memtorch code. Thanks to this memtorch code, it helped a lot, but I have a question, so I want to ask you a question. I would like to ask you a question about how VTEAM corrects the values of these parameters, such as r_on, r_off, etc., to reduce accuracy and increase accuracy. In conclusion, please tell me how to modify the values of the parameters.

May I ask you a question? Have you ever encountered memory crashes when testing with a patched model? If so, how was it resolved?
