### ISSUE TITLE
How to save the patched model?

### ISSUE THREAD

**Issue by RTCartist** [coreylammie/MemTorch#157]
When I try to save the patched model using this way
`torch.save(patched_model, 'patched_model.pth')`
It will encounter false. So the only way to save this patched model is using the function 
`torch.save(patched_model.state_dict(), 'patched_model_state_dict.pth')` Right?

**Comment by sheep1222** [comment]
我想问一下，您是使用的GPU版本还是CPU版本，如果是GPU，我想问您是如何解决调整线性层时，Python内核死掉的问题？如果是CPU，我将restnet18的卷积层和线性层都修补后，用修补的模型进行测试，会出现内存不够用的情况，我的内存是30G，这是正常情况吗？

**Comment by RTCartist** [comment]
> 我想问一下，您是使用的GPU版本还是CPU版本，如果是GPU，我想问您是如何解决调整线性层时，Python内核死掉的问题？如果是CPU，我将restnet18的卷积层和线性层都修补后，用修补的模型进行测试，会出现内存不够用的情况，我的内存是30G，这是正常情况吗？

Hello, the version I chose is the GPU version, and I find that the python kernel death is quite common (mainly due to the MEMTorch itself) and the only way to deal with it to simplify the linear neural network you designed.

**Comment by sheep1222** [comment]
How do I understand what you mean by simplified linear networks, which means fewer neurons?

**Comment by sheep1222** [comment]
> > 我想问一下，您是使用的GPU版本还是CPU版本，如果是GPU，我想问您是如何解决调整线性层时，Python内核死掉的问题？如果是CPU，我将restnet18的卷积层和线性层都修补后，用修补的模型进行测试，会出现内存不够用的情况，我的内存是30G，这是正常情况吗？
> 
> Hello, the version I chose is the GPU version, and I find that the python kernel death is quite common (mainly due to the MEMTorch itself) and the only way to deal with it to simplify the linear neural network you designed.

How do I understand what you mean by simplified linear networks, which means fewer neurons?

**Comment by RTCartist** [comment]
Right, you should reduce the number of layers and neurons.

**Comment by sheep1222** [comment]
> torch.save(patched_model.state_dict(), 'patched_model_state_dict.pth')

As a beginner, thank you very much for patiently answering my questions. Additionally, I would like to know if you have conducted any experiments related to reloading the patched model for testing?

**Comment by RTCartist** [comment]
Not yet. I think the proper way is to save the original trained model. In
next use, you can reload the trained model, then use the same memristor
parameters to patch this model. I believe it works, though I haven't tried
it yet.
