### ISSUE TITLE
showing error while trying to install memtorch (on google collab and jupyter)

### ISSUE THREAD

**Issue by charanecer12** [coreylammie/MemTorch#159]
hi , i have tried installing memtorch package by all given methods,but it  is throwing error during the process
i have attached the screenshot of it
<img width="538" alt="err_mem" src="https://github.com/coreylammie/MemTorch/assets/114241600/33eb6cd9-fc3c-44e8-ac7d-fb9d3727f95a">

**Comment by KunalRandad** [comment]
Hey @charanecer12 , did you find the solution to this, I am facing the same problem right now as well!

**Comment by 24367452** [comment]
did you find the solution to this, I am facing the same problem right now as well!

**Comment by KunalRandad** [comment]
@24367452 No, I could not resolve this issue. I thus switched to aihwkit by IBM. Let me know if you find solution to this.

**Comment by 24367452** [comment]
Hello, are there any other frameworks that can replace memtorch to implement memristive neural networks


> 不，我无法解决此问题。因此，我切换到了 IBM 的 aihwkit。如果您找到解决方案，请告诉我。

**Comment by KunalRandad** [comment]
Try aihwkit by IBM

**Comment by sheep1222** [comment]
> Try aihwkit by IBM

You  can change the setup.py's install_requires,line99,sklearn->scikit-learn，because the name of the sklearn library has been changed! How about IBM's aihwkit? I'm not using it well. If you're using it well, please let me know. I also know DNN_NovoroSim_V2.1, but I don't know how to configure it. If you have tried this, please let me know.

**Comment by spectacles9468** [comment]
Did anybody try again on colab? I changed the sklearn in setup but it's still giving me error:
![image](https://github.com/coreylammie/MemTorch/assets/55502062/5c9ea181-e874-470d-bed9-ebd3b3f819b5)

**Comment by sheep1222** [comment]
> Did anybody try again on colab? I changed the sklearn in setup but it's still giving me error: ![image](https://private-user-images.githubusercontent.com/55502062/321536580-5c9ea181-e874-470d-bed9-ebd3b3f819b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjA0MzksIm5iZiI6MTcxMjgyMDEzOSwicGF0aCI6Ii81NTUwMjA2Mi8zMjE1MzY1ODAtNWM5ZWExODEtZTg3NC00NzBkLWJlZDktZWJkM2IzZjgxOWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA3MjIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYTNiYTg2MTIyMmUzZDBlMjEwNWQwOTBhYzVjM2ZhMmQzNThhY2NjMWUwN2RmYjVjNTExOGU5YWQ1NTI3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.scOeFqxUoQVK4z_Bfi8wS2P3JSlJscQZZba8VaJE9Ec)


you should install eigen first

**Comment by spectacles9468** [comment]
Did you mean pip install eigency? But, it's giving the same error

**Comment by sheep1222** [comment]
> Did you mean pip install eigency? But, it's giving the same error
run these in the terminal,i didn't try in the colab
git clone https://gitlab.com/libeigen/eigen.git
cd eigen
mkdir build
cd build
cmake ..
make
make install

**Comment by spectacles9468** [comment]
Is there any way to use it in colab because the tutorial is given in colab?

**Comment by 24367452** [comment]
Hello, I have been trying to use IBM's aihwkit recently, but when I run the following simple example
```
from torch import Tensor
from aihwkit.nn import AnalogLinear

model = AnalogLinear(2, 2)
model(Tensor([[0.1, 0.2], [0.3, 0.4]]))
```
The following error occurred:
```
C:\Users\Administrator\.conda\envs\cq\python.exe E:/aihwkit_CNN/test.py
Traceback (most recent call last):
  File "E:\aihwkit_CNN\test.py", line 2, in <module>
    from aihwkit.nn import AnalogLinear
  File "C:\Users\Administrator\.conda\envs\cq\lib\site-packages\aihwkit\nn\__init__.py", line 17, in <module>
    from aihwkit.nn.modules.container import AnalogSequential, AnalogWrapper
  File "C:\Users\Administrator\.conda\envs\cq\lib\site-packages\aihwkit\nn\modules\container.py", line 23, in <module>
    from aihwkit.nn.modules.base import AnalogLayerBase
  File "C:\Users\Administrator\.conda\envs\cq\lib\site-packages\aihwkit\nn\modules\base.py", line 22, in <module>
    from aihwkit.simulator.tiles.module import TileModule
  File "C:\Users\Administrator\.conda\envs\cq\lib\site-packages\aihwkit\simulator\tiles\__init__.py", line 17, in <module>
    from aihwkit.simulator.tiles.analog import AnalogTile
  File "C:\Users\Administrator\.conda\envs\cq\lib\site-packages\aihwkit\simulator\tiles\analog.py", line 21, in <module>
    from aihwkit.simulator.tiles.rpucuda import RPUCudaSimulatorTileWrapper
  File "C:\Users\Administrator\.conda\envs\cq\lib\site-packages\aihwkit\simulator\tiles\rpucuda.py", line 24, in <module>
    from aihwkit.simulator.parameters.base import RPUConfigGeneric
  File "C:\Users\Administrator\.conda\envs\cq\lib\site-packages\aihwkit\simulator\parameters\__init__.py", line 31, in <module>
    from .training import UpdateParameters
  File "C:\Users\Administrator\.conda\envs\cq\lib\site-packages\aihwkit\simulator\parameters\training.py", line 20, in <module>
    from .helpers import _PrintableMixin
  File "C:\Users\Administrator\.conda\envs\cq\lib\site-packages\aihwkit\simulator\parameters\helpers.py", line 20, in <module>
    from aihwkit.simulator import rpu_base
ImportError: DLL load failed while importing rpu_base: The specified module could not be found.
```
May I ask what I should do and how can I solve this problem? @KunalRandad

**Comment by KunalRandad** [comment]
@24367452 Looks like some issue in installation. I would recommend to use google colab to see if error persists. Incase it still does, cross check the code with examples at https://github.com/IBM/aihwkit/tree/master/examples
