### ISSUE TITLE
Power/Area/Timing Estimate Report

### ISSUE THREAD

**Issue by coreylammie** [coreylammie/MemTorch#22]
In a future release, power, area and timing estimate reports are to be generated.

**Comment by Jize-W** [comment]
> In a future release, power, area and timing estimate reports are to be generated.

Hello!
Recently I need to use the function of estimating power, area and latency. When will the second version be released? Could you give me some guidance on how to make a rough estimate? Thanks a lot.

**Comment by coreylammie** [comment]
Hi Jize-W,

Apologies for the delayed response- this functionality is likely to be added by the end of April. Progress is currently delayed, as I am developing an empirical Metal-Oxide RRAM device endurance and retention model for a separate project. Once published, I will integrate this within MemTorch so device endurance and retention characteristics can be accounted for.

In the paper '_Towards Memristive Deep Learning Systems for Real-time Mobile Epileptic Seizure Prediction_' ([https://arxiv.org/pdf/2102.08555.pdf](https://arxiv.org/pdf/2102.08555.pdf)) I roughly determined power, area, latency, and energy requirements for a Time-Division Multiplexed (TDM) configuration, in which each tile contained one ADC that is TDM between columns, and a parallelized configuration, in which each tile contained one ADC per column to read out column currents in parallel. 

Analog to Digital Converters (ADCs) and RRAM cells consume most of the area and power, so the area and power can simply be approximated by negating other components. Most assumptions were taken from '_A Deep Neural Network Accelerator Based on Tiled RRAM Architecture_' ([https://ieeexplore.ieee.org/document/8993641](https://ieeexplore.ieee.org/document/8993641)), that references a datasheet from an undisclosed vendor. As a general rule-of-thumb, the maximum read voltage used during inference shouldn't exceed +/- 0.3V. This is discussed in detail in '_Impact of Read Disturb on Multilevel RRAM based Inference Engine: Experiments and Model Prediction_' ([https://dl.acm.org/doi/10.1109/IRPS45951.2020.9129252](https://dl.acm.org/doi/10.1109/IRPS45951.2020.9129252)).

Hopefully this helps! Feel free to ask any more specific questions if you have them.

Kind Regards,

Corey.
