### ISSUE TITLE
Error Running Tutorial.ipynb

### ISSUE THREAD

**Issue by OlisDS** [coreylammie/MemTorch#41]
Running in Conda Virtual Environment, have tried building from source and installing memtorch via pip.

ImportError                               Traceback (most recent call last)
<ipython-input-2-015d8b6a4e9b> in <module>
      1 import torch
      2 from torch.autograd import Variable
----> 3 import memtorch
      4 import torch.nn as nn
      5 import torch.nn.functional as F

D:\Anaconda\envs\memTorch\lib\site-packages\memtorch\__init__.py in <module>
      2 import torch
      3 from memtorch.bh import *
----> 4 from memtorch.bh.nonideality import *
      5 from memtorch.mn import *
      6 from memtorch.utils import *

D:\Anaconda\envs\memTorch\lib\site-packages\memtorch\bh\nonideality\__init__.py in <module>
----> 1 from .NonIdeality import *
      2 from .FiniteConductanceStates import *

D:\Anaconda\envs\memTorch\lib\site-packages\memtorch\bh\nonideality\NonIdeality.py in <module>
      1 import memtorch
      2 import memtorch.mn
----> 3 from memtorch.bh.nonideality.FiniteConductanceStates import apply_finite_conductance_states
      4 from memtorch.bh.nonideality.DeviceFaults import apply_device_faults
      5 from memtorch.bh.nonideality.NonLinear import apply_non_linear

D:\Anaconda\envs\memTorch\lib\site-packages\memtorch\bh\nonideality\FiniteConductanceStates.py in <module>
      3 import numpy as np
      4 if 'cpu' in memtorch.__version__:
----> 5     import quantization
      6 else:
      7     import cuda_quantization as quantization

**Comment by coreylammie** [comment]
Hi OlisDS,

Thanks for reaching out! Unfortunately, it looks like the log you have provided is incomplete. To help me identify the issue, could you please specify the exact commands you have issued, and post the full output from each.  `command > log.txt` can be used to direct output to a text document, that can be directly attached to a comment here for sake-of-convenience.

In addition, could you please specify (1) your operating system, (2) the version of python that your conda environment is using, and (3) confirm that you have installed Microsoft Visual C++ Build Tools?

Kind Regards,

Corey.
