### ISSUE TITLE
Is CUDA a prerequisite?

### ISSUE THREAD

**Issue by AmD99** [coreylammie/MemTorch#95]
I tried to install memtorch by using the coommand "pip install memtorch" but get an error saying- "**CUDA_HOME environment variable is not set. Please set it to your CUDA install root**"
I do not have CUDA as I am using a machine that does not have an NVIDIA graphic card on it.
Is there any way around this? Pls see the screenshot of the error attached.
Thank you!
![Screenshot from 2021-09-18 22-51-57](https://user-images.githubusercontent.com/51073924/133904330-826e9eea-0b81-4f74-a4fd-e753be3228a2.png)

**Comment by coreylammie** [comment]
Hi @AmD99,

The CPU (non-CUDA) version of memtorch can be installed using `pip install memtorch-cpu`.

Kind Regards,

Corey.

**Comment by AmD99** [comment]
Thank you so much! @coreylammie
